import '@/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
// import { AppBar } from '@mui/material'
import LayoutView from '@/views/layout/layout-view';
import { AuthProvider } from '@/context/auth-context';
import { MessageProvider } from '@/context/message-context';
import LoginView from '@/views/login/login-view';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='m-0'>
        <AuthProvider>
          <MessageProvider>
            <LayoutView>
              {/* <LoginView/> */}
              {children}
            </LayoutView>
          </MessageProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
