import "@/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import { AppBar } from '@mui/material'
import LayoutView from "@/views/layout/layout-view";
import { AuthProvider } from "@/context/auth-context";
import { MessageProvider } from "@/context/message-context";
import LoginView from "@/views/auth/login/login-view";
import Head from "next/head";
import PetsIcon from "@mui/icons-material/Pets";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "憨吉寵物-Hangi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // {
  //   icon: '/paw-solid.svg',
  // }
  return (
    <html lang="en">
      <body className="m-0 background-image">
        <AuthProvider>
          <MessageProvider>
            <LayoutView>
              {/* <LoginView/> */}
              {children}
            </LayoutView>
          </MessageProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
